Adding static linking potential.
coreylowman/cudarc pull request #104
Opened 2023-03-24 18:15 UTC by Narsil

When building binaries with cuda, the dependency on the libs is super large.

Biggest culprit is cublasLt which is 485Mb on its own.
Using static linking, shrinks everything into the binary which becomes ~130Mo (after stripping) in my case.
It also makes cublas loading much faster.

I chose to use an env variable for the type of linking since it avoids introducing new features and bloating the code with them.

Feel free to ignore if you don't deem this worthy !

2023-03-24 18:48 UTC, coreylowman requested changes
I like this change, definitely want to add it in!

2023-03-24 18:48 UTC, coreylowman commented on build.rs
> +        println!("cargo:rustc-link-lib=dylib=stdc++");
Do we need this one?

2023-03-24 18:48 UTC, coreylowman commented on build.rs
> +    println!("cargo:rustc-link-lib=static=cudart_static");
Didn't realize until this PR, but we can actually remove this lib all together - we don't use any runtime apis

2023-03-24 18:48 UTC, coreylowman commented on build.rs
> +    let is_static = std::env::var("STATIC").unwrap_or_else(|_| "0".to_string()) == "1";
Let's go with feature flag, it's more reproducible than environment variable and I think fits better within rust ecosystem at least.

2023-03-25 08:53 UTC, Narsil commented
Superseeded by https://github.com/coreylowman/cudarc/pull/105 (allows me to keep my main for experimentation).

2023-03-25 08:53 UTC, closed without merging