Minimum changes for occupancy API
coreylowman/cudarc pull request #180
Opened 2023-09-15 23:40 UTC by Jark5455

Hello,

Here is a draft pull request for #102

2023-09-18 14:45 UTC, coreylowman requested changes
Look good to me, can you run `cargo fmt` and then I can merge

2023-09-18 17:24 UTC, Jark5455 commented
I believe it is failing because of a change that isn't made by me. The `Cudnn::new` function is returning an Arc to a Cudnn handle even though it shouldn't be able to since Cudnn handles are not thread safe.

2023-09-19 16:28 UTC, coreylowman commented
Actually you don't need to fix the Arc, I can fix that separately - Can you revert that change but keep the cargo fmt? I will manually merge even though the piplines fail 😄

2023-09-21 01:13 UTC, Jark5455 commented
Sorry about that, im struggling with git a bit, I think its good now.

2023-09-25 13:00 UTC, merged